"""Propose a fix as a GitHub pull request.

Takes a FixDraft (from fixer.py) plus the analyzer's risk report and opens a
real PR via the GitHub REST API using only urllib. The token comes from the
`GITHUB_TOKEN` environment variable — never from argv, so it stays out of
shell history and process listings.
"""
from __future__ import annotations

import json
import urllib.error
import urllib.request

from . import __version__
from .fixer import FixDraft
from .models import DeprecationEntry, Finding

API_BASE = "https://api.github.com"


def build_pr_body(entry: DeprecationEntry, draft: FixDraft,
                  findings: list[Finding] | None = None) -> str:
    """Render the PR body: risk summary, diff, contract test, and notes."""
    lines = [
        "## 🤖 Integration-rot autopilot",
        "",
        f"Automated migration draft for **{entry.vendor}**: {entry.title}.",
        "",
    ]
    if findings:
        f = findings[0]
        lines.append(f"**Risk:** `{f.risk.upper()}`"
                     + (f" — sunsets {f.entry.sunset}" if f.entry.sunset else ""))
        lines.append("")
    lines.append(f"**Migration guide:** {entry.migration}")
    if entry.source_url:
        lines.append(f"**Vendor source:** {entry.source_url}")
    lines.append("")
    lines.append("### Changes")
    lines.append("")
    for change in draft.changes:
        lines.append(f"`{change.path}`")
        lines.append("```diff")
        lines.append(change.diff.rstrip())
        lines.append("```")
        lines.append("")
    if draft.tests:
        lines.append("### Contract test")
        lines.append("")
        lines.append("Generated and attached — run it in CI before merging:")
        lines.append("")
        for test_path, content in draft.tests:
            lines.append(f"`{test_path}`")
            lines.append("```python")
            lines.append(content.rstrip())
            lines.append("```")
            lines.append("")
    if draft.notes:
        lines.append("### Reviewer notes")
        lines.append("")
        for note in draft.notes:
            lines.append(f"- {note}")
        lines.append("")
    lines.append("---")
    lines.append(f"_Generated by integration-rot v{__version__}. "
                 "This is a draft — please review carefully before merging._")
    return "\n".join(lines)


def open_pr(owner: str, repo: str, head: str, base: str, title: str,
            body: str, token: str, draft_pr: bool = False) -> dict:
    """Open a pull request. Returns the parsed PR JSON (incl. `html_url`).

    Raises RuntimeError with the API's error message on failure.
    """
    url = f"{API_BASE}/repos/{owner}/{repo}/pulls"
    payload = {"title": title, "head": head, "base": base,
               "body": body, "draft": draft_pr}
    req = urllib.request.Request(
        url,
        data=json.dumps(payload).encode("utf-8"),
        headers={"Accept": "application/vnd.github+json",
                 "Authorization": f"Bearer {token}",
                 "X-GitHub-Api-Version": "2022-11-28"},
        method="POST",
    )
    try:
        with urllib.request.urlopen(req, timeout=30) as resp:
            return json.loads(resp.read().decode("utf-8"))
    except urllib.error.HTTPError as e:
        try:
            detail = json.loads(e.read().decode("utf-8"))
            message = detail.get("message", str(e))
        except Exception:
            message = str(e)
        raise RuntimeError(f"GitHub API error opening PR: {message}") from e
